/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formulario;

import com.mycompany.javavendass.Dados;
import com.mycompany.javavendass.Dados_db;
import com.mycompany.javavendass.Opcoes;
import com.mycompany.javavendass.Produto;
import com.mycompany.javavendass.Usuario;
import com.mycompany.javavendass.Utilidades;
import com.mysql.cj.conf.PropertyKey;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeCellRenderer;


/**
 *
 * @author Arthur
 */
public class frmFatura extends javax.swing.JInternalFrame {

        private Dados msDados;
        
        private Dados_db msDados_db;
        
        private DefaultTableModel mTabela;
    
    public void setDados(Dados msDados){
    this.msDados = msDados;
    }
    
    public void setDados_db(Dados_db msDados_db){
    this.msDados_db = msDados_db;
    }
    
    
    public frmFatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        cmbUsuario = new javax.swing.JComboBox<>();
        cmbProduto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalhes = new javax.swing.JTable();
        btnDeletar = new javax.swing.JButton();
        btnAdiconar = new javax.swing.JButton();
        btnDeletarTodos = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("quantidade:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("produto:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("usuario:");

        cmbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioActionPerformed(evt);
            }
        });

        tblDetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalhes);

        btnDeletar.setText("deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnAdiconar.setText("adcionar");
        btnAdiconar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdiconarActionPerformed(evt);
            }
        });

        btnDeletarTodos.setText("deletar tudo");
        btnDeletarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarTodosActionPerformed(evt);
            }
        });

        btnSalvar.setText("salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("valor:");

        txtQuant.setEnabled(false);
        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });

        txtValor.setEnabled(false);
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbProduto, 0, 281, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnAdiconar)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar)
                .addGap(28, 28, 28)
                .addComponent(btnDeletarTodos)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdiconar)
                    .addComponent(btnDeletar)
                    .addComponent(btnDeletarTodos)
                    .addComponent(btnSalvar))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(cmbUsuario.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(rootPane, "por favor selecione um cliente");
        cmbUsuario.requestFocusInWindow();
        return;
        }
        int totalquant = Integer.parseInt(txtQuant.getText());
        if(totalquant==0){
            JOptionPane.showMessageDialog(rootPane,"por favor insirir os produtos ");
            cmbProduto.requestFocusInWindow();
            return;
        }
        
        int numFatura = msDados_db.getNumeroFatura();
          msDados_db.adicionarFatura(numFatura,((Opcoes)cmbUsuario.getSelectedItem()).getValor()
                   );
        
       
        
        
        int num = tblDetalhes.getRowCount();
            
            for(int i = 0; i <num; i++){
                msDados_db.adicionarDetalheFatura(
                        numFatura,
                        i,
                        Utilidades.objectToString(tblDetalhes.getValueAt(i, 0)),
                        Utilidades.objectToString(tblDetalhes.getValueAt(i, 1)),
                        Utilidades.objectToInt(tblDetalhes.getValueAt(i, 2)),
                        Utilidades.objectToInt(tblDetalhes.getValueAt(i, 3)));
                
                

                
            }
            
                
        
    JOptionPane.showMessageDialog(rootPane, "venda feita com sucesso");
        
        cmbUsuario.setSelectedIndex(0);
        Limpartabela();
        totais();
        cmbUsuario.requestFocusInWindow();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioActionPerformed
        if (cmbProduto.getSelectedIndex ()==0) {
    JOptionPane.showMessageDialog(rootPane, "FAVOR, SELECIONAR PRODUTO. !"); 
    cmbProduto.requestFocusInWindow();
    return;
        }
    }//GEN-LAST:event_cmbUsuarioActionPerformed

    private void btnAdiconarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdiconarActionPerformed
        if (cmbProduto.getSelectedIndex ()==0) {
    JOptionPane.showMessageDialog(rootPane, "FAVOR, SELECIONAR PRODUTO. !"); 
    cmbProduto.requestFocusInWindow();
    return;
        }

        if (txtQuantidade.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "FAVOR DIGITAR UMA QUANTIDADE.!");
         txtQuantidade.requestFocusInWindow();
        return;
        }
        
         if(!Utilidades.isNumeric(txtQuant.getText())){
            JOptionPane.showMessageDialog(rootPane, "por favor inserir um numero numerico");
            txtQuantidade.setText("");
            txtQuantidade.requestFocusInWindow();
            return;
                }
         
        int quantidade = Integer.parseInt(txtQuantidade.getText());
        if(quantidade <= 0){
            JOptionPane.showMessageDialog(rootPane, "por favor inserir um numero acima de 0");
            txtQuantidade.requestFocusInWindow();
            txtQuantidade.setText("");
            return;
                }
        Produto mProduto = msDados_db.getProduto(((Opcoes)cmbProduto.getSelectedItem()).getValor());
        
        String registro[] = new String[5];
        registro[0] = mProduto.getIdProduto();
        registro[1] = mProduto.getDescricao();
        registro[2] = "" + mProduto.getPreco();
        registro[3] = "" + quantidade;
        //registro[4] = "" + (quantidade* mProduto.getPreco()); 
        registro[4] = "" + (mProduto.getPreco() + (mProduto.getPreco() * quantidade / 100.0));
        mTabela.addRow(registro);
        
        cmbProduto.setSelectedIndex(0);
        txtQuantidade.setText("");
        cmbProduto.requestFocusInWindow();
        totais();
           
        
          
         
    }//GEN-LAST:event_btnAdiconarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       
        try{ 
        Opcoes opc = new Opcoes("teste@gmail.com", "selecione um cliente");
        cmbUsuario.addItem(opc);
            ResultSet rsUsu = msDados_db.getUsuarios();
        while (rsUsu.next()){
            opc = new Opcoes(
       rsUsu.getString("id"),
            rsUsu.getString("nome")+""+
            rsUsu.getString("sobrenome"));
        cmbUsuario.addItem(opc);
        }
         
        opc = new Opcoes("teste@gmail.com", "selecione um produto");
        cmbProduto.addItem(opc);
            ResultSet rsPro = msDados_db.getProdutos();
        while (rsPro.next()){
            opc = new Opcoes(
       rsPro.getString("idProduto"),
    rsPro.getString("descricao"));
        cmbProduto.addItem(opc);
        }
        //txtData.setText(Utilidades.formatDate(new Date()));
        txtQuant.setText("0");
        txtValor.setText("0");
        
        preencherTabela();
        }catch (SQLException ex ){
            Logger.getLogger(frmFatura.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        





    }//GEN-LAST:event_formInternalFrameOpened

    private void btnDeletarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarTodosActionPerformed
         int resposta = JOptionPane.showConfirmDialog(rootPane, "voce tem certeza que deseja excluir essa venda");
        if(resposta !=0){
            return;
   
        }
        Limpartabela();
        totais();
    }//GEN-LAST:event_btnDeletarTodosActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if (cmbProduto.getSelectedIndex ()==0) {
    JOptionPane.showMessageDialog(rootPane, "FAVOR, SELECIONAR PRODUTO. !"); 
    cmbProduto.requestFocusInWindow();
    return;
        }
        try{
        DefaultTableModel modelo = (DefaultTableModel)tblDetalhes.getModel();
        int linha = tblDetalhes.getRowCount();
        for(int i =0 ; linha> i ; i++){
            String idTabela = Utilidades.objectToString(tblDetalhes.getValueAt(i, 0));
            String idCombo = ((Opcoes)cmbProduto.getSelectedItem()).getValor();
            if(idTabela.equals(idCombo)){
        modelo.removeRow(i);
        totais();
        return;
            }
        }
    }catch (Exception e ){
        e.printStackTrace();
    }

         


    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdiconar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnDeletarTodos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Opcoes> cmbProduto;
    private javax.swing.JComboBox<Opcoes> cmbUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalhes;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

 private void preencherTabela(){
    String titulos[]= {"idProd","descriçao","preço","quant","valor"};
    String registro[] = new String[5];
    mTabela = new DefaultTableModel(null,titulos);
        tblDetalhes.setModel(mTabela);
        
        
        
 }
private void totais() {
    int num = tblDetalhes.getRowCount();
    int somQuant = 0, somVal = 0;
    
    for (int i = 0; i < num; i++) {
        somQuant += Utilidades.objectToInt(tblDetalhes.getValueAt(i, 3));
        somVal += Utilidades.objectToInt(tblDetalhes.getValueAt(i, 4));
    }
    
    txtQuant.setText(""+somQuant);
    // Define o texto do campo txtVal com o valor calculado de somVal
    txtValor.setText(""+somVal);
}

            
public void Limpartabela(){
    try{
        DefaultTableModel modelo = (DefaultTableModel)tblDetalhes.getModel();
        int linha = tblDetalhes.getRowCount();
        for(int i =0 ; linha> i ; i++){
        modelo.removeRow(0);
        }
    }catch (Exception e ){
        e.printStackTrace();
    }

}

    




}










 
