/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formulario;

import com.mycompany.javavendass.Dados;
import com.mycompany.javavendass.Dados_db;
import com.mycompany.javavendass.Produto;
import com.mycompany.javavendass.Utilidades;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class frmProdutos extends javax.swing.JInternalFrame {
     private Dados msDados;
     
     private Dados_db msDados_db;
     
     private int prodAtual =0;
     private boolean novo = false;
     private DefaultTableModel mTabela;
    
    public void setDados(Dados msDados){
    this.msDados = msDados;
    }
    
    public void setDados_db(Dados_db msDados_db){
    this.msDados_db = msDados_db;
    }
    
    public frmProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbImposto = new javax.swing.JComboBox<>();
        buttonPrimeiro = new javax.swing.JButton();
        buttonProximo = new javax.swing.JButton();
        buttonAnterior = new javax.swing.JButton();
        buttonUltimo = new javax.swing.JButton();
        buttonPesquisar = new javax.swing.JButton();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        buttonExcluirProduto = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnotacao = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Empresa:");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("id empresa:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("descriçao:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("preço :");

        txtIdProduto.setEnabled(false);

        txtDescricao.setEnabled(false);
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        txtPreco.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("comissão:");

        cmbImposto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "15%" }));
        cmbImposto.setEnabled(false);
        cmbImposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImpostoActionPerformed(evt);
            }
        });

        buttonPrimeiro.setText("primeiro");
        buttonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrimeiroActionPerformed(evt);
            }
        });

        buttonProximo.setText("proximo");
        buttonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProximoActionPerformed(evt);
            }
        });

        buttonAnterior.setText("anterior");
        buttonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnteriorActionPerformed(evt);
            }
        });

        buttonUltimo.setText("ultimo");
        buttonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUltimoActionPerformed(evt);
            }
        });

        buttonPesquisar.setText("pesquisar");
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });

        buttonNovo.setText("novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonSalvar.setText("salvar");
        buttonSalvar.setEnabled(false);
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonExcluirProduto.setText("excluir");
        buttonExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirProdutoActionPerformed(evt);
            }
        });

        buttonCancelar.setText("cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("anotação:");

        txtAnotacao.setColumns(20);
        txtAnotacao.setRows(5);
        jScrollPane2.setViewportView(txtAnotacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonPrimeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(buttonExcluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cmbImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(168, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPesquisar)
                    .addComponent(buttonUltimo)
                    .addComponent(buttonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProximo)
                    .addComponent(buttonPrimeiro))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo)
                    .addComponent(buttonEditar)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonExcluirProduto)
                    .addComponent(buttonCancelar))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbImpostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImpostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImpostoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        buttonPrimeiro.setEnabled(false);
        buttonAnterior.setEnabled(false);
        buttonProximo.setEnabled(false);
        buttonUltimo.setEnabled(false);
        buttonNovo.setEnabled(false);
        buttonEditar.setEnabled(false);
        buttonExcluirProduto.setEnabled(false);
        buttonPesquisar.setEnabled(false);
        buttonSalvar.setEnabled(true);
        buttonCancelar.setEnabled(true);
        //caixa text
        txtDescricao.setEnabled(true);
        txtPreco.setEnabled(true);
        txtAnotacao.setEnabled(true);
        cmbImposto.setEnabled(true);
       
        novo = false;
        
        txtDescricao.requestFocus();
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnteriorActionPerformed
        prodAtual--;
        if(prodAtual== -1){
         prodAtual = msDados_db.numeroUsuarios() -1;
         
         
        }
        mostrarRegistro();
    }//GEN-LAST:event_buttonAnteriorActionPerformed

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        buttonPrimeiro.setEnabled(false);
        buttonAnterior.setEnabled(false);
        buttonProximo.setEnabled(false);
        buttonUltimo.setEnabled(false);
        buttonNovo.setEnabled(false);
        buttonEditar.setEnabled(false);
        buttonExcluirProduto.setEnabled(false);
        buttonPesquisar.setEnabled(false);
        buttonSalvar.setEnabled(true);
        buttonCancelar.setEnabled(true);
        //caixa text
        txtIdProduto.setEnabled(true);
        txtDescricao.setEnabled(true);
        txtPreco.setEnabled(true);
        txtAnotacao.setEnabled(true);
        cmbImposto.setEnabled(true);
        //limpeza das caixasde textos
         txtIdProduto.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtAnotacao.setText("");
        cmbImposto.setSelectedIndex(0);
        
        novo = true;
        
        txtIdProduto.requestFocus();
        
        
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        if(txtIdProduto.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "por favor inserir um numero de id");
            txtIdProduto.requestFocusInWindow();
            return;
                }
        
        if(cmbImposto.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(rootPane, "por favor selecionar uma comissão");
            cmbImposto.requestFocusInWindow();
            return;
                }
        
         if(txtDescricao.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "por favor inserir uma descriçao");
            txtDescricao.requestFocusInWindow();
            return;
                }
         
          if(txtPreco.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "por favor inserir um preço");
            txtPreco.requestFocusInWindow();
            return;
                }
          
          int preco = Integer.parseInt(txtPreco.getText());
        if(preco <= 0){
            JOptionPane.showMessageDialog(rootPane, "por favor inserir um numero acima de 0");
            txtPreco.requestFocusInWindow();
            return;
                }
          
          if(!Utilidades.isNumeric(txtPreco.getText())){
            JOptionPane.showMessageDialog(rootPane, "por favor inserir um preço");
            txtPreco.requestFocusInWindow();
            return;
                }
          
          
           
           
           if(novo){
           if(msDados_db.existeProduto(txtIdProduto.getText())){
               JOptionPane.showMessageDialog(rootPane, "este produto ja existe");
            txtIdProduto.requestFocusInWindow();
            return;
           }
           }else {
            if (!msDados_db.existeProduto(txtIdProduto.getText())) {
               JOptionPane.showMessageDialog(rootPane, "Este produto não existe");
            txtIdProduto.requestFocusInWindow();
            return;
    }
}
                
Produto mProduto = new Produto(
    txtIdProduto.getText(),
    txtDescricao.getText(),
    preco,
    cmbImposto.getSelectedIndex(),
    txtAnotacao.getText()
);

                 
           String msg;
           if(novo){
           msg =  msDados_db.adicionarProduto(mProduto);
           }
           else{
               msg =  msDados_db.editarProduto(mProduto );
               
           }
               
               
           JOptionPane.showMessageDialog(rootPane, msg);
              
           
        
        buttonPrimeiro.setEnabled(true);
        buttonAnterior.setEnabled(true);
        buttonProximo.setEnabled(true);
        buttonUltimo.setEnabled(true);
        buttonNovo.setEnabled(true);
        buttonEditar.setEnabled(true);
        buttonExcluirProduto.setEnabled(true);
        buttonPesquisar.setEnabled(true);
        buttonSalvar.setEnabled(false);
        buttonCancelar.setEnabled(false); 
         //distabilazar o campos
        txtIdProduto.setEnabled(false);
        txtDescricao.setEnabled(false);
        txtPreco.setEnabled(false);
        txtAnotacao.setEnabled(false);
        cmbImposto.setEnabled(false);
        preencherTabela();
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        buttonPrimeiro.setEnabled(true);
        buttonAnterior.setEnabled(true);
        buttonProximo.setEnabled(true);
        buttonUltimo.setEnabled(true);
        buttonNovo.setEnabled(true);
        buttonEditar.setEnabled(true);
        buttonExcluirProduto.setEnabled(true);
        buttonPesquisar.setEnabled(true);
        buttonSalvar.setEnabled(false);
        buttonCancelar.setEnabled(false);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      preencherTabela();
      mostrarRegistro();
      
      
       
       
       
       
    }//GEN-LAST:event_formInternalFrameOpened

    private void buttonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrimeiroActionPerformed
        prodAtual = 0;
         mostrarRegistro();
        
    }//GEN-LAST:event_buttonPrimeiroActionPerformed

    private void buttonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUltimoActionPerformed
        prodAtual = msDados_db.numeroUsuarios() - 1;
        mostrarRegistro();


    }//GEN-LAST:event_buttonUltimoActionPerformed

    private void buttonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProximoActionPerformed
       prodAtual++;
       if(prodAtual== msDados_db.numeroUsuarios()){
           prodAtual = 0;
       }
       mostrarRegistro();

    }//GEN-LAST:event_buttonProximoActionPerformed

    private void buttonExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirProdutoActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "voce tem certeza que deseja excluir esse produto");
        if(resposta !=0){
            return;
   
        }
        String msg;
        msg = msDados_db.excluirProduto(txtIdProduto.getText());
         JOptionPane.showMessageDialog(rootPane,msg);
         prodAtual=0;
         preencherTabela();  
         mostrarRegistro();
           
    
    }//GEN-LAST:event_buttonExcluirProdutoActionPerformed

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarActionPerformed
        String Produto = JOptionPane.showInputDialog("favor inserir o codigo do usuario");
        if(Produto.equals("")){
            return;
        }
        
        if(!msDados_db.existeProduto(Produto)){
           JOptionPane.showMessageDialog(rootPane, "este produto não existe");  
           return;
        }
        int num = tblTabela.getRowCount();
            
            for(int i = 0; i <num; i++){
            if(Utilidades.objectToString(tblTabela.getValueAt(i, 0)).equals(Produto)){
                prodAtual=i;
                break;
            }
            
            }
                
        mostrarRegistro();
        
    }//GEN-LAST:event_buttonPesquisarActionPerformed
        
    private void mostrarRegistro(){
       
    txtIdProduto.setText(Utilidades.objectToString(tblTabela.getValueAt(prodAtual, 0)));
    txtDescricao.setText(Utilidades.objectToString(tblTabela.getValueAt(prodAtual, 1)));
    txtPreco.setText(Utilidades.objectToString(tblTabela.getValueAt(prodAtual, 2)));
    txtAnotacao.setText(Utilidades.objectToString(tblTabela.getValueAt(prodAtual, 3)));
    cmbImposto.setSelectedIndex(imposto(Utilidades.objectToString(tblTabela.getValueAt(prodAtual, 4))));
}
    
    private void preencherTabela(){
        try{
    String titulos[]= {"id","descrição","preço","comissão","anotação"};
    String registro[] = new String[5];
    mTabela = new DefaultTableModel(null,titulos);
    ResultSet rs = msDados_db.getProdutos();
             
             while(rs.next()){
                 registro[0]= rs.getString("idProduto");
                 registro[1]= rs.getString("descricao");
                 registro[2]= rs.getString("preco");
                 registro[3]= imposto(rs.getInt("idImposto"));
                 registro[4]= rs.getString("notas");
                 
                 mTabela.addRow(registro);
             }
             tblTabela.setModel(mTabela);
             } catch (SQLException ex) {
             Logger.getLogger(frmProdutos.class.getName()).log(Level.SEVERE, null, ex);
         }
            }
    
    
    private String imposto(int idIMPOSTO){
    switch(idIMPOSTO){
        case 0: return"0%";
        case 1: return"10%";
        case 2: return"15%";
        default: return"não definido";
        
    }
    }
    private int imposto(String IMPOSTO){
        if(IMPOSTO.equals("0%")){
            return 0;
        
    }else if(IMPOSTO.equals("10%")){
    return 1;
    }else {
    return 2;
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnterior;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluirProduto;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JButton buttonPrimeiro;
    private javax.swing.JButton buttonProximo;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JButton buttonUltimo;
    private javax.swing.JComboBox<String> cmbImposto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextArea txtAnotacao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
