/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import com.mycompany.javavendass.Dados;
import com.mycompany.javavendass.Dados_db;


/**
 *
 * @author Arthur
 */
public class frmPrincipal extends javax.swing.JFrame {
   
    private String senha;
    private String usuario;
    private Dados msDados;
    
    
    private Dados_db msDados_db;
    
    public void setDados(Dados msDados){
    this.msDados = msDados;
    }
   
    public void setDados_db(Dados_db msDados_db){
    this.msDados_db = msDados_db;
    }
    
    public void setUsuario(String usuario){
    this.usuario = usuario;
    }
    
    public void setSenha(String senha){
    this.senha = senha;
    }

    
    
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuArquivosProdutos = new javax.swing.JMenuItem();
        mnuArquivosUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuArquivostSenha = new javax.swing.JMenuItem();
        mnuArquivostUser = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuArquivosSair = new javax.swing.JMenuItem();
        mnuMovimentos = new javax.swing.JMenu();
        mnuMovimentosNovaVenda = new javax.swing.JMenuItem();
        mnuMovimentosRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sistema");

        deskPainel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout deskPainelLayout = new javax.swing.GroupLayout(deskPainel);
        deskPainel.setLayout(deskPainelLayout);
        deskPainelLayout.setHorizontalGroup(
            deskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        deskPainelLayout.setVerticalGroup(
            deskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        mnuArquivos.setText("arquivos");

        mnuArquivosProdutos.setText("produtos");
        mnuArquivosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivosProdutosActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuArquivosProdutos);

        mnuArquivosUsuarios.setText("usuario");
        mnuArquivosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivosUsuariosActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuArquivosUsuarios);
        mnuArquivos.add(jSeparator1);

        mnuArquivostSenha.setText("redefinir senha");
        mnuArquivostSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivostSenhaActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuArquivostSenha);

        mnuArquivostUser.setText("trocar usuario");
        mnuArquivostUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivostUserActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuArquivostUser);
        mnuArquivos.add(jSeparator2);

        mnuArquivosSair.setText("sair");
        mnuArquivosSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivosSairActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuArquivosSair);

        jMenuBar1.add(mnuArquivos);

        mnuMovimentos.setText("movimentos");

        mnuMovimentosNovaVenda.setText("nova venda");
        mnuMovimentosNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosNovaVendaActionPerformed(evt);
            }
        });
        mnuMovimentos.add(mnuMovimentosNovaVenda);

        mnuMovimentosRelatorio.setText("relatorio");
        mnuMovimentosRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosRelatorioActionPerformed(evt);
            }
        });
        mnuMovimentos.add(mnuMovimentosRelatorio);

        jMenuBar1.add(mnuMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArquivostSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivostSenhaActionPerformed
        frmTrocarSenha msSenha = new frmTrocarSenha(this,rootPaneCheckingEnabled);
        msSenha.setLocationRelativeTo(null);
        msSenha.setSenha(senha);
        msSenha.setUsuario(usuario);
        msSenha.setDados(msDados);
        
        msSenha.setDados_db(msDados_db);
        
        msSenha.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuArquivostSenhaActionPerformed

    private void mnuArquivosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivosUsuariosActionPerformed
        frmUsuarios mUsuarios = new frmUsuarios();
        //mUsuarios.setDados(msDados);
        
        mUsuarios.setDados_db(msDados_db);
        
        deskPainel.add(mUsuarios);
        mUsuarios.setVisible(true);

        
        
    }//GEN-LAST:event_mnuArquivosUsuariosActionPerformed

    private void mnuArquivosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivosProdutosActionPerformed
        frmProdutos msProdutos = new frmProdutos();
        msProdutos.setDados(msDados);
        
        msProdutos.setDados_db(msDados_db);
        
        deskPainel.add(msProdutos);
        msProdutos.setVisible(true);
    }//GEN-LAST:event_mnuArquivosProdutosActionPerformed

    private void mnuArquivosSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivosSairActionPerformed
        msDados.salvarTodo();
        System.exit(0);
    }//GEN-LAST:event_mnuArquivosSairActionPerformed

    private void mnuArquivostUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivostUserActionPerformed
        this.setVisible(false);
        frmLogin mLogin = new frmLogin();
        mLogin.setDados(msDados);
        mLogin.setLocationRelativeTo(null);
        mLogin.setVisible(true);
    }//GEN-LAST:event_mnuArquivostUserActionPerformed

    private void mnuMovimentosNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosNovaVendaActionPerformed
        frmFatura mFatura = new frmFatura();
        mFatura.setDados(msDados);
        
        mFatura.setDados_db(msDados_db);
        
        deskPainel.add(mFatura);
        mFatura.show();
   
    }//GEN-LAST:event_mnuMovimentosNovaVendaActionPerformed

    private void mnuMovimentosRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosRelatorioActionPerformed
        frmRelatoriosVendas mRelatorio = new frmRelatoriosVendas();
        mRelatorio.setDados(msDados);
        
        mRelatorio.setDados_db(msDados_db);
        
        deskPainel.add(mRelatorio);
        mRelatorio.show();
    }//GEN-LAST:event_mnuMovimentosRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuItem mnuArquivosProdutos;
    private javax.swing.JMenuItem mnuArquivosSair;
    private javax.swing.JMenuItem mnuArquivosUsuarios;
    private javax.swing.JMenuItem mnuArquivostSenha;
    private javax.swing.JMenuItem mnuArquivostUser;
    private javax.swing.JMenu mnuMovimentos;
    private javax.swing.JMenuItem mnuMovimentosNovaVenda;
    private javax.swing.JMenuItem mnuMovimentosRelatorio;
    // End of variables declaration//GEN-END:variables
}
